
container:
  image:
    repository: 405157225880.dkr.ecr.eu-west-3.amazonaws.com/dixneuf19/demo-k8s # TODO add tf output
    tag: latest
    pullPolicy: Always
  port: 8080
  resources:
    limits:
      memory: '256Mi'
      cpu: '1'
    requests:
      memory: '128Mi'
      cpu: '1'
  probe:
    path: /healthz
    timeoutSeconds: 10
  liveness:
    scheme: HTTP
    initialDelaySeconds: 300
    periodSeconds: 30
    timeoutSeconds: 10
  maxSurge: 2
  maxUnavailable: 0
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  averageCpuUtilization: 70
service:
  type: ClusterIP
  port: 80
