apiVersion: v1
name: gitlab-runner
description: A deployment of gitlab-runner
type: application
version: 0.1.0
dependencies:
  - name: gitlab-runner
    repository: https://charts.gitlab.io
    version: 0.41.0
