gitlab-runner:
  gitlabUrl: https://gitlab.com
  runnerRegistrationToken: FIX_ME # To update if you change the Gitlab group

  terminationGracePeriodSeconds: 3600
  concurrent: 200
  checkInterval: 5

  rbac:
    create: true
    rules:
      - apiGroups: ["*"]
        resources: ["*"]
        verbs: ["*"]
    clusterWideAccess: true
    serviceAccountAnnotations:
      eks.amazonaws.com/role-arn: FIX_ME # Set the ARN of the role you created for the gitlab-runner, see terraform outputs

  runners:
    config: |
      listen_address = ":9252"
      [[runners]]
        [runners.kubernetes]
          image = "ubuntu:20.04"
          namespace = "gitlab"
          poll_timeout = 600
          cpu_request = "2000m"
          cpu_limit = "4000m"
          memory_request = "1Gi"
          memory_limit = "2Gi"
          helper_memory_request = "256Mi"
          helper_memory_limit = "1000Mi"
          service_memory_request = "64Mi"
          service_memory_limit = "256Mi"
          service_account = "gitlab-runner"
          privileged = true
          [runners.kubernetes.pod_labels]
            ci_executor = "$CI_RUNNER_DESCRIPTION"
            ci_job = "$CI_BUILD_ID"
          [[runners.kubernetes.volumes.empty_dir]]
            name = "docker-certs"
            mount_path = "/certs/client"
            medium = "Memory"
        [runners.feature_flags]
          FF_SCRIPT_SECTIONS = true
          FF_GITLAB_REGISTRY_HELPER_IMAGE = true
    executor: kubernetes
    tags: "kubernetes,padok"

  resources:
    requests:
      cpu: 500m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 256Mi
